### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by Kubuxu** [NOVAAPI/NovaCore#21]
We need permission to licence this repository (NovaCore) under LGPLv3:

- [x] @asiekierka 
- [x] @stanhebben 
- [x] @calclavia 
- [x] @RX14 
- [x] @Kubuxu
- [x] @magik6k 
- [x] @Thog92 
- [x] @Vexatos 

EDIT: We have permission to licence at 4f86d0c7262ba538506896989301c7c9ad78f775. Thank you all.

**Comment by Vexatos** [comment]
Permission granted.

**Comment by Thog92** [comment]
Permission granted.

**Comment by asiekierka** [comment]
Permission granted.

**Comment by RX14** [comment]
Permission granted

**Comment by calclavia** [comment]
Permission granted.

**Comment by stanhebben** [comment]
Permission granted.

**Comment by magik6k** [comment]
Permission granted.
