### ISSUE TITLE
.obj renderer cannot render UV coordinates past 1.0 in either coordinate direction.

### ISSUE THREAD

**Issue by ellisong** [NOVAAPI/NovaCore#44]
My model had a face where the UV coordinate of the face was past 1.0 in the U direction. In-game, this face did not render until the coordinates of the face's UV was in-between 0.0 and 1.0. Not sure if intended.

![](http://i.imgur.com/a1LU8Uq.png)
![](http://i.imgur.com/ESvxmii.png)

**Comment by calclavia** [comment]
Moved to: http://tracker.calclavia.com/issues?q=project%3A+NOVA#
