### ISSUE TITLE
Repository Naming

### ISSUE THREAD

**Issue by calclavia** [NOVAAPI/NovaCore#76]
Just for convention's sake, do you think we should rename all repositories like this?

Use dashes between capitalized words is the current convention for Github repositories.
"NOVA-Core"
"NOVA-Wrapper-MC"

Also, our group should be called "NOVA-API".

Currently we have a bunch of repositories with different conventions. This might be trivial and cost minor hassle, but it'll look more profesisonal/nicer in the long run. If we do rename it, now is the chance, since NOVA is not widely used yet.

**Comment by RX14** [comment]
Our group should technically be called `NOVAPI`

**Comment by RX14** [comment]
I would suggest just calling the repositories "core" "wrapper-minecraft" "microblocks". They are already in the NOVA org.

**Comment by RX14** [comment]
In addition to that point, I think renaming all of our stuff is going to be more trouble than it is worth.

**Comment by gamemanj** [comment]
Forks, though, are *not* in the NOVA org, so it gets confusing outside there.

**Comment by RX14** [comment]
good point, i did not think of that

**Comment by Victorious3** [comment]
As long as you don't start to use Micro-Blocks, I'm all fine with it ^^

**Comment by calclavia** [comment]
Then I think we have consensus here. I'll change the repository names. Please update your remote addresses. :) Thanks.

**Comment by RX14** [comment]
You don't actually need to change anything, github automatically redirects.
